package ld.ui;

import arc.*;
import arc.scene.style.*;
import arc.scene.ui.Button.*;
import arc.scene.ui.CheckBox.*;
import arc.scene.ui.Dialog.*;
import arc.scene.ui.ImageButton.*;
import arc.scene.ui.KeybindDialog.*;
import arc.scene.ui.Label.*;
import arc.scene.ui.ScrollPane.*;
import arc.scene.ui.Slider.*;
import arc.scene.ui.TextButton.*;
import arc.scene.ui.TextField.*;

//Autogenerated, do not touch.
public class Tex{
    public static NinePatchDrawable checkOn, buttonDown, checkOver, buttonOver, button, border, scroll, window, checkOff;
    public static TextureRegionDrawable sliderKnob, blank, sliderKnobOver, slider, selection, scrollKnobVertical, cursor, white, sliderKnobDown;

    public static void load(){
        checkOn = Core.atlas.getDrawable("check-on");
        sliderKnob = Core.atlas.getDrawable("slider-knob");
        buttonDown = Core.atlas.getDrawable("button-down");
        blank = Core.atlas.getDrawable("blank");
        checkOver = Core.atlas.getDrawable("check-over");
        buttonOver = Core.atlas.getDrawable("button-over");
        button = Core.atlas.getDrawable("button");
        border = Core.atlas.getDrawable("border");
        scroll = Core.atlas.getDrawable("scroll");
        window = Core.atlas.getDrawable("window");
        sliderKnobOver = Core.atlas.getDrawable("slider-knob-over");
        slider = Core.atlas.getDrawable("slider");
        selection = Core.atlas.getDrawable("selection");
        checkOff = Core.atlas.getDrawable("check-off");
        scrollKnobVertical = Core.atlas.getDrawable("scroll-knob-vertical");
        cursor = Core.atlas.getDrawable("cursor");
        white = Core.atlas.getDrawable("white");
        sliderKnobDown = Core.atlas.getDrawable("slider-knob-down");
    }

    public static void register(){
        Core.scene.addStyle(ButtonStyle.class, Styles.defaultb);
        Core.scene.addStyle(TextButtonStyle.class, Styles.defaultt);
        Core.scene.addStyle(ImageButtonStyle.class, Styles.defaulti);
        Core.scene.addStyle(ScrollPaneStyle.class, Styles.defaultPane);
        Core.scene.addStyle(DialogStyle.class, Styles.defaultWindow);
        Core.scene.addStyle(SliderStyle.class, Styles.defaultSlider);
        Core.scene.addStyle(LabelStyle.class, Styles.defaultLabel);
        Core.scene.addStyle(TextFieldStyle.class, Styles.defaultField);
        Core.scene.addStyle(CheckBoxStyle.class, Styles.defaultCheck);
        Core.scene.addStyle(KeybindDialogStyle.class, Styles.defaultKeybind);
    }
}