package ld.ui;

import arc.*;
import arc.scene.style.*;

//Autogenerated, do not touch.
public class Tex{
    public static NinePatchDrawable checkOn, buttonDown, checkOver, buttonOver, button, border, scroll, window, checkOff;
    public static TextureRegionDrawable sliderKnob, blank, sliderKnobOver, slider, selection, scrollKnobVertical, cursor, white, sliderKnobDown;

    public static void load(){
        checkOn = Core.atlas.getDrawable("check-on");
        sliderKnob = Core.atlas.getDrawable("slider-knob");
        buttonDown = Core.atlas.getDrawable("button-down");
        blank = Core.atlas.getDrawable("blank");
        checkOver = Core.atlas.getDrawable("check-over");
        buttonOver = Core.atlas.getDrawable("button-over");
        button = Core.atlas.getDrawable("button");
        border = Core.atlas.getDrawable("border");
        scroll = Core.atlas.getDrawable("scroll");
        window = Core.atlas.getDrawable("window");
        sliderKnobOver = Core.atlas.getDrawable("slider-knob-over");
        slider = Core.atlas.getDrawable("slider");
        selection = Core.atlas.getDrawable("selection");
        checkOff = Core.atlas.getDrawable("check-off");
        scrollKnobVertical = Core.atlas.getDrawable("scroll-knob-vertical");
        cursor = Core.atlas.getDrawable("cursor");
        white = Core.atlas.getDrawable("white");
        sliderKnobDown = Core.atlas.getDrawable("slider-knob-down");
    }
}